<a href="https://colab.research.google.com/github/mahdiskj/SupportVectorRegression/blob/main/support_vector_regression_GH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Support Vector Regression (SVR)

## Importing the libraries

In [36]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [37]:
dataset = pd.read_csv('MSFT.csv')
dataset = dataset.drop(columns="Date")
dataset.head()

Open        High         Low       Close   Adj Close    Volume
0  177.139999  180.639999  176.309998  180.119995  178.231873  36433300
1  184.029999  184.199997  178.410004  179.899994  178.014191  39186300
2  180.970001  183.820007  180.059998  183.630005  181.705093  27751400
3  182.850006  185.630005  182.479996  183.889999  181.962357  33529100
4  183.580002  188.839996  183.250000  188.699997  186.721939  35844300

In [38]:
X = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:, -1].values
print(X)

[[177.139999 180.639999 176.309998 180.119995 178.231873]
 [184.029999 184.199997 178.410004 179.899994 178.014191]
 [180.970001 183.820007 180.059998 183.630005 181.705093]
 ...
 [235.059998 242.5      232.429993 239.649994 239.649994]
 [241.300003 242.309998 238.690002 239.509995 239.509995]
 [239.570007 245.089996 239.259995 243.       243.      ]]


In [39]:
# the scaler class expect a 2-D array as input 
y = y.reshape(len(y),1)

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

## Feature Scaling

In [41]:
# because the dependant and independant variables are way different in scale, ...
# ...it's better to convert them into somehow same scales (x & y)
# we also need to rescale them back into original scales to have an accurate prediction and visualization
from sklearn.preprocessing import StandardScaler
# we don't use the same standard scaler object for x and y because they are way different ...
# ... and we want an accurate scaling based on x and y values seperately
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

X_test = sc_X.fit_transform(X_test)
y_test = sc_y.fit_transform(y_test)

In [42]:
print(X_train)

[[-0.76028027 -0.65326606 -0.66295156 -0.54506859 -0.54263886]
 [ 0.24793248  0.36490574  0.35235797  0.29843513  0.3054416 ]
 [ 0.74364415  0.76989851  0.83603645  0.84594767  0.84260909]
 ...
 [ 0.7399134   0.66461941  0.73966916  0.681972    0.68173131]
 [ 0.92131699  0.90457968  0.95176858  0.95665455  0.97735407]
 [-2.19985049 -2.21063714 -2.17577162 -2.28210193 -2.26158964]]


## Training the SVR model on the whole dataset

In [43]:
from sklearn.svm import SVR
# the kernel is adapted with different kinds of data, here we have polynomial data so we use 'rbf' (radial basis function)
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

## Predicting a new result

In [44]:
# we must reverse the scaling now, because if we don't we'll actually see the scaled result as well and it's not our interest
# sc_X.transform([[6.5]]) : the model was rained on scaled data, so to get a proper output, we need to scale our new input by the same scaler
# sc_y.inverse_transform : the output withuot this finction will be in the scaled mode, too...
#... we should reverse the scaling to go back to the original sclae of the predicted output.
y_pred=sc_y.inverse_transform(regressor.predict(X_test))
print(y_pred)

[32603775.26325317 45499469.91816276 25447560.83996712 27347715.66611401
 34051868.7466249  25274887.23374837 38390306.92292266 30633924.4454717
 26201200.69573077 33110209.49930487 30939844.73137898 34109505.0781259
 31006699.28325015 32926937.13649088 26085578.19121896 33412161.74088878
 27224435.93238357 33429092.13966255 65003652.1037617  32561524.61428787
 26745211.13422912 66923223.43147755 34985257.34311809 30626571.11049755
 30164040.16402817 25798783.69955047 36849488.19205575 27300464.75207167
 56469511.60653266 27166667.78900655 28001318.36614846 43939475.61961868
 33717858.73056886 25348795.72675727 36281885.39293722 42825299.65949941
 52014301.03328599 71037723.24345723 42040613.38264525 26781275.67493628
 31939043.58330397 45778903.61100532 32865309.96175176 33184786.92495392
 77940470.005868   25533827.42482757 65345575.90030096 34825499.9860617
 71760262.85114494 32860484.23556805 27213282.6167594 ]
